
INSERT INTO MASTER_ITEMS(ID,ITEM_NAME,PRICE,CREATION_DATE) VALUES ('1','PURI',50, now());
INSERT INTO MASTER_ITEMS(ID,ITEM_NAME,PRICE,CREATION_DATE) VALUES ('2','CHAPATI',50, now());
INSERT INTO MASTER_ITEMS(ID,ITEM_NAME,PRICE,CREATION_DATE) VALUES ('3','RICE',50, now());
INSERT INTO MASTER_ITEMS(ID,ITEM_NAME,PRICE,CREATION_DATE) VALUES ('4','IDLY',50, now());
INSERT INTO MASTER_ITEMS(ID,ITEM_NAME,PRICE,CREATION_DATE) VALUES ('5','DOSA',50, now());
INSERT INTO MASTER_ITEMS(ID,ITEM_NAME,PRICE,CREATION_DATE) VALUES ('6','BREAKFAST SANDWICH',50, now());

INSERT INTO TX_ORDERS(ID,ITEM_NAME,SOLD_DATE,NUMBER_OF_ORDERS_TODAY) VALUES ('1','PURI', now(),1);
INSERT INTO TX_ORDERS(ID,ITEM_NAME,SOLD_DATE,NUMBER_OF_ORDERS_TODAY) VALUES ('2','CHAPATI', now(),1);
INSERT INTO TX_ORDERS(ID,ITEM_NAME,SOLD_DATE,NUMBER_OF_ORDERS_TODAY) VALUES ('3','RICE', now(),1);
INSERT INTO TX_ORDERS(ID,ITEM_NAME,SOLD_DATE,NUMBER_OF_ORDERS_TODAY) VALUES ('4','IDLY', now(),1);
INSERT INTO TX_ORDERS(ID,ITEM_NAME,SOLD_DATE,NUMBER_OF_ORDERS_TODAY) VALUES ('5','DOSA', now(),1);
INSERT INTO TX_ORDERS(ID,ITEM_NAME,SOLD_DATE,NUMBER_OF_ORDERS_TODAY) VALUES ('6','BREAKFAST SANDWICH', now(),1);